#!/usr/bin/env bash
# AminoCloud standardized entrypoint — generated by seed-ac-dirs.sh
# Runtime environment variables (injected by the AC pipeline worker):
#   AC_INPUT_<PORT_ID_UPPER>   path to each declared input file/dir
#   AC_OUTPUT_DIR              write all outputs here
#   AC_CPU_THREADS             allocated vCPU count (integer)
#   AC_MEMORY_GB               allocated memory in GB (integer)
#   AC_JOB_ID                  pipeline job UUID (for log correlation)
#   AC_STEP_ID                 job step UUID (for log correlation)
set -euo pipefail
mkdir -p "${AC_OUTPUT_DIR}"

cutadapt \
    -j "${AC_CPU_THREADS}" \
    -o "${AC_OUTPUT_DIR}/trimmed.fastq.gz" \
    "${AC_INPUT_FASTQ_IN}"
